[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
build_src_filter = +<*> -<.git/> -<.svn/>
build_flags = 
    -I include
    -I lib/FreeRTOS/include
    -I lib/FreeRTOS/portable/GCC/ARM_CM3