[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
build_src_filter = +<*> -<.git/> -<.svn/>
build_flags = 
    -I include
    -I lib/FreeRTOS/include
    -I lib/FreeRTOS/portable/GCC/ARM_CM3

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<alarm_logic.cpp> +<display_navigation.cpp> +<system_state_logic.cpp>
build_flags = -I include